import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { LoginContainer, MainContainer } from "../styles/style";
import { NormalInput } from "../src/components/index";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <LoginContainer>
          <div>
            <NormalInput></NormalInput>
          </div>
        </LoginContainer>
      </MainContainer>
    </>
  );
};

export default Home;
